import type { CleanzAgentStatus } from "@/lib/agent/types";

export function getCleanzAgentNetwork(aiCoreReady = false): CleanzAgentStatus[] {
  const aiHealth = aiCoreReady ? "online" : "blocked";
  const memoryStatus = aiCoreReady ? "connected" : "mock memory";
  const executionHistory = aiCoreReady ? ["Connected to Henry IV real AI core"] : ["Waiting for a valid OpenAI connection"];

  return [
    {
      name: "CEO Agent",
      domain: "Founder leverage, prioritization, capital allocation",
      health: aiHealth,
      activeMission: "Rank the highest leverage Cleanz bottlenecks.",
      taskQueue: ["Review opportunities", "Prepare founder briefing", "Flag strategic risks"],
      reportingCadence: "Every briefing",
      permissionScope: "Recommend only",
      memoryStatus,
      executionHistory,
    },
    {
      name: "Operations Agent",
      domain: "Bookings, cleaners, job flow, issue recovery",
      health: aiHealth,
      activeMission: "Monitor missed calls and staffing gaps.",
      taskQueue: ["Scan booking flow", "Prepare approval queue", "Detect open issues"],
      reportingCadence: "Live dashboard",
      permissionScope: "Read and draft",
      memoryStatus,
      executionHistory,
    },
    {
      name: "Sales Agent",
      domain: "Lead recovery, upsells, abandoned bookings",
      health: aiHealth,
      activeMission: "Identify unconverted leads.",
      taskQueue: ["Find dormant leads", "Draft follow-ups", "Spot recurring-clean opportunities"],
      reportingCadence: "Midday and nightly",
      permissionScope: "Draft only",
      memoryStatus,
      executionHistory,
    },
    {
      name: "Marketing Agent",
      domain: "Campaigns, reviews, website conversion",
      health: aiHealth,
      activeMission: "Find weak conversion and review-response gaps.",
      taskQueue: ["Scan review queue", "Draft campaign ideas", "Monitor website health"],
      reportingCadence: "Nightly",
      permissionScope: "Recommend and draft",
      memoryStatus,
      executionHistory,
    },
    {
      name: "Finance Agent",
      domain: "Revenue, refunds, pricing, cleaner pay risk",
      health: "blocked",
      activeMission: "Monitor entered revenue until Stripe is approved.",
      taskQueue: ["Summarize revenue", "Flag refund approvals", "Model pricing changes"],
      reportingCadence: "Every briefing",
      permissionScope: "Read-only; money actions approval-required",
      memoryStatus,
      executionHistory: ["Blocked live finance execution"],
    },
    {
      name: "Customer Success Agent",
      domain: "Customer issues, follow-up, retention, churn risk",
      health: aiHealth,
      activeMission: "Surface unresolved customer issues.",
      taskQueue: ["Draft replies", "Find churn risk", "Recommend retention actions"],
      reportingCadence: "Live dashboard",
      permissionScope: "Draft only",
      memoryStatus,
      executionHistory,
    },
    {
      name: "Acquisitions Agent",
      domain: "Cedar Neck Realty deal sourcing, single-family leads, multifamily leads, seller and broker follow-up",
      health: aiHealth,
      activeMission: "Prepare acquisition sourcing briefs and rank follow-up targets.",
      taskQueue: ["Build deal watchlist", "Draft seller outreach", "Prepare underwriting checklist"],
      reportingCadence: "Morning and on command",
      permissionScope: "Read, recommend, and draft; outreach approval-required",
      memoryStatus,
      executionHistory,
    },
    {
      name: "Developer Agent",
      domain: "Code, architecture, reliability, deployment readiness",
      health: aiHealth,
      activeMission: "Stage XENOMORPH handoffs and protect production.",
      taskQueue: ["Review architecture", "Draft code plans", "Block unsafe pushes"],
      reportingCadence: "On command",
      permissionScope: "Draft and recommend; code push approval-required",
      memoryStatus,
      executionHistory,
    },
    {
      name: "Recruiting Agent",
      domain: "Cleaner recruiting, onboarding, capacity planning",
      health: aiHealth,
      activeMission: "Find coverage gaps and recruiting needs.",
      taskQueue: ["Scan staffing gaps", "Draft recruiting tasks", "Prepare onboarding checklist"],
      reportingCadence: "Nightly",
      permissionScope: "Recommend and draft",
      memoryStatus,
      executionHistory,
    },
    {
      name: "Scheduling Agent",
      domain: "Calendar, dispatch, cleaner availability",
      health: "blocked",
      activeMission: "Schedule monitoring waits for Calendar approval.",
      taskQueue: ["Check availability", "Draft schedule changes", "Prepare calendar-event approvals"],
      reportingCadence: "Morning and midday",
      permissionScope: "Read and draft; calendar changes approval-required",
      memoryStatus,
      executionHistory: ["Blocked live calendar execution"],
    },
  ];
}
